# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

install:
  - pip install -r requirements.txt
  - bash tests/make_isis_env.sh

before_script:
    - flake8 pysis

script: ISISROOT=/tmp/pysis/isis py.test tests
